### The Deutsch-Jozsa algorithm

Implement the $U_f$ gate for a general black box (or oracle) function $f: \{0,1\}^n \rightarrow \{0,1\}$. We don't want to simulate the auxiliary qubit explicitly, so the action of the $U_f$ gate is an added phase $(-1)^{f(x)}$ on each basis state x. Let's be super clear on what we mean by this: The computational basis consists of $2^n$ states: $\{|00..0\rangle, |00..01\rangle.., |11..1\rangle  \}$. The bitstring $x$ that enters into the black box function is the binary array of length $n$ that describes the state of each qubit for a given basis state. We can also enumerate  the basis states with the integer numbers $x$ running from $0$ to $2^n-1$. Now the bitstring $x$ is simply the list of binary digits of the integer number $x$. This identification of the "index" of the basis state with the corresponding "state" of the qubits will also be crucial for the other quantum algorithms like the quantum Fourier transform.

np.abs() mean (take the absolute value (the magnitude) of each number in an array)

How the algorithm work?

1- Initialize two registers
   - n-qubit input in state |0⟩^n
   - 1-qubit output in state |1⟩
2- Apply Hadamard gates to all qubit → put them into superposition
3- Apply the oracle Uf (black-box that compute f(x))
4- Apply Hadamard gates again to input qubit
5- Complete the Algorithm
6- Measured the qubit

In [1]:
from quantum_algorithms import (
    I, X, Z, P0, P1, H, Y, CNOT,
    controlled_gate, U_N_qubits,
    initial_state, apply_hadamards,
    sample_probs, oracle_function, 
    deutsch_jozsa,
    f_constant_0,
    f_constant_1,
    f_balanced_parity,
    measure_probs_first_n,
    sample_measurements_input,
)

In [2]:
import numpy as np
from collections import Counter
n = 2

state_const = deutsch_jozsa(n, f_constant_0)
state_bal = deutsch_jozsa(n, f_balanced_parity)

probs_const = measure_probs_first_n(state_const, n)
probs_bal = measure_probs_first_n(state_bal, n)

print("P(|0^n>) constant =", probs_const[0])
print("P(|0^n>) balanced =", probs_bal[0])

P(|0^n>) constant = 0.9999999999999989
P(|0^n>) balanced = 2.643498704767422e-34


In [3]:
probs_bal

array([2.64349870e-34, 1.00000000e+00, 5.28699741e-34, 2.64349870e-34])

In [4]:
probs_const

array([1.00000000e+00, 2.64349870e-34, 2.64349870e-34, 5.28699741e-34])

In [5]:
import numpy as np
from collections import Counter
n = 1

state_const = deutsch_jozsa(n, f_constant_0)
state_bal = deutsch_jozsa(n, f_balanced_parity)

probs_const = measure_probs_first_n(state_const, n)
probs_bal = measure_probs_first_n(state_bal, n)

print("P(|0^n>) constant =", probs_const[0])
print("P(|0^n>) balanced =", probs_bal[0])

P(|0^n>) constant = 0.9999999999999996
P(|0^n>) balanced = 1.0573994819069698e-33


In [6]:
probs_const

array([1.00000000e+00, 1.05739948e-33])

In [7]:
probs_bal

array([1.05739948e-33, 1.00000000e+00])

In [8]:
# Measure both cases
shots = 1024
n = 9

state_const = deutsch_jozsa(n, f_constant_1)
state_bal   = deutsch_jozsa(n, f_balanced_parity)

samples_const = sample_measurements_input(state_const, n, shots)
samples_bal   = sample_measurements_input(state_bal, n, shots)

print("\nMeasurement samples (constant):", samples_const)
print("Measurement samples (balanced):", samples_bal)


Measurement samples (constant): Counter({0: 1024})
Measurement samples (balanced): Counter({1: 1024})


In [9]:
# Measure both cases
shots = 2000
n = 11

state_const = deutsch_jozsa(n, f_constant_1)
state_bal   = deutsch_jozsa(n, f_balanced_parity)

samples_const = sample_measurements_input(state_const, n, shots)
samples_bal   = sample_measurements_input(state_bal, n, shots)

print("\nMeasurement samples (constant):", samples_const)
print("Measurement samples (balanced):", samples_bal)


Measurement samples (constant): Counter({0: 2000})
Measurement samples (balanced): Counter({1: 2000})


In [10]:
# Measure both cases
shots = 3000
n = 7

state_const = deutsch_jozsa(n, f_constant_1)
state_bal   = deutsch_jozsa(n, f_balanced_parity)

samples_const = sample_measurements_input(state_const, n, shots)
samples_bal   = sample_measurements_input(state_bal, n, shots)

print("\nMeasurement samples (constant):", samples_const)
print("Measurement samples (balanced):", samples_bal)


Measurement samples (constant): Counter({0: 3000})
Measurement samples (balanced): Counter({1: 3000})


In [11]:
# Measure both cases
shots = 7000
n = 6

state_const = deutsch_jozsa(n, f_constant_1)
state_bal   = deutsch_jozsa(n, f_balanced_parity)

samples_const = sample_measurements_input(state_const, n, shots)
samples_bal   = sample_measurements_input(state_bal, n, shots)

print("\nMeasurement samples (constant):", samples_const)
print("Measurement samples (balanced):", samples_bal)


Measurement samples (constant): Counter({0: 7000})
Measurement samples (balanced): Counter({1: 7000})


In [12]:
# Measure both cases
shots = 10000
n = 9

state_const = deutsch_jozsa(n, f_constant_1)
state_bal   = deutsch_jozsa(n, f_balanced_parity)

samples_const = sample_measurements_input(state_const, n, shots)
samples_bal   = sample_measurements_input(state_bal, n, shots)

print("\nMeasurement samples (constant):", samples_const)
print("Measurement samples (balanced):", samples_bal)


Measurement samples (constant): Counter({0: 10000})
Measurement samples (balanced): Counter({1: 10000})
