### The Deutsch-Jozsa algorithm

Implement the $U_f$ gate for a general black box (or oracle) function $f: \{0,1\}^n \rightarrow \{0,1\}$. We don't want to simulate the auxiliary qubit explicitly, so the action of the $U_f$ gate is an added phase $(-1)^{f(x)}$ on each basis state x. Let's be super clear on what we mean by this: The computational basis consists of $2^n$ states: $\{|00..0\rangle, |00..01\rangle.., |11..1\rangle  \}$. The bitstring $x$ that enters into the black box function is the binary array of length $n$ that describes the state of each qubit for a given basis state. We can also enumerate  the basis states with the integer numbers $x$ running from $0$ to $2^n-1$. Now the bitstring $x$ is simply the list of binary digits of the integer number $x$. This identification of the "index" of the basis state with the corresponding "state" of the qubits will also be crucial for the other quantum algorithms like the quantum Fourier transform.

np.abs() mean (take the absolute value (the magnitude) of each number in an array)


In [1]:
from quantum_algorithms import ( 
    I, X, Z, P0, P1, H, Y,
    controlled_gate, U_N_qubits,
    initial_state, apply_hadamards,
    sample_probs, oracle_function, 
    deutsch_jozsa,
    f_constant_0,
    f_constant_1,
    f_balanced_parity,
    measure_probs_first_n,
    sample_measurements_input,
)

In [15]:
import numpy as np
from collections import Counter
n = 2

state_c = deutsch_jozsa(n, f_constant_0)
state_b = deutsch_jozsa(n, f_balanced_parity)

probs_c = measure_probs_first_n(state_c, n)
probs_b = measure_probs_first_n(state_b, n)

print("P(0) constant:\n", probs_c[0])
print("P(0) balanced:\n", probs_b[0])

P(0) constant:
 0.9999999999999989
P(0) balanced:
 2.643498704767422e-34


In [3]:
probs_b

array([2.64349870e-34, 1.00000000e+00, 5.28699741e-34, 2.64349870e-34])

In [4]:
probs_c

array([1.00000000e+00, 2.64349870e-34, 2.64349870e-34, 5.28699741e-34])

In [5]:
import numpy as np
from collections import Counter
n = 1

state_const = deutsch_jozsa(n, f_constant_0)
state_bal = deutsch_jozsa(n, f_balanced_parity)

probs_const = measure_probs_first_n(state_const, n)
probs_bal = measure_probs_first_n(state_bal, n)
print("P(0) constant =", probs_const[0])
print("P(0) balanced =", probs_bal[0])

P(0) constant = 0.9999999999999996
P(0) balanced = 1.0573994819069698e-33


In [6]:
probs_c

array([1.00000000e+00, 2.64349870e-34, 2.64349870e-34, 5.28699741e-34])

In [7]:
probs_b

array([2.64349870e-34, 1.00000000e+00, 5.28699741e-34, 2.64349870e-34])

In [8]:
# Measure both cases
shots = 1024
n = 9

state_c = deutsch_jozsa(n, f_constant_1)
state_b = deutsch_jozsa(n, f_balanced_parity)
samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j  1.08967808e-20+0.j ...
  1.08967808e-20+0.j  1.08967808e-20+0.j -1.08967808e-20+0.j]

 state balanced:
 [-1.08967808e-20+0.j  1.08967808e-20+0.j  7.07106781e-01+0.j ...
  1.08967808e-20+0.j  1.08967808e-20+0.j -1.08967808e-20+0.j]

Measurement samples (constant):
 Counter({np.int64(0): 1024})

Measurement samples (balanced):
 Counter({np.int64(1): 1024})


In [9]:
# Measure both cases
shots = 2000
n = 11

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j -7.89214680e-20+0.j ...
  0.00000000e+00+0.j  0.00000000e+00+0.j  0.00000000e+00+0.j]

 state balanced:
 [ 7.89214680e-20+0.j -7.89214680e-20+0.j  7.07106781e-01+0.j ...
  0.00000000e+00+0.j  0.00000000e+00+0.j  0.00000000e+00+0.j]

Measurement samples (constant):
 Counter({np.int64(0): 2000})

Measurement samples (balanced):
 Counter({np.int64(1): 2000})


In [10]:
# Measure both cases
shots = 3000
n = 7

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j  2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j -1.94518072e-18+0.j
  1.94518072e-18+0.j  2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -5.41462768e-18+0.j  5.41462768e-18+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j  2.10457248e-19+0.j
 -2.10457248e-19+0.j -2.10457248e-19+0.j  2.10457248e-19+0.j
 -1.52426623e-18+0.j  1.52426623e-18+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j  2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j -5.41462768e-18+0.j
  5.41462768e-18+0.j  2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -1.52426623e-18+0.j  1.52426623e-18+0.j
 -2.10457248e-19+0.j  2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j  2.10457248e-19+0.j -2.10457248e-19+0.j
 -1.52

In [11]:
# Measure both cases
shots = 7000
n = 6 

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j -2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j -3.17181546e-18+0.j
  3.17181546e-18+0.j -2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  3.76707845e-18+0.j -3.76707845e-18+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j -2.97631495e-19+0.j
  2.97631495e-19+0.j  2.97631495e-19+0.j -2.97631495e-19+0.j
 -3.76707845e-18+0.j  3.76707845e-18+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j -2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j  1.76448663e-17+0.j
 -1.76448663e-17+0.j -2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j -3.76707845e-18+0.j  3.76707845e-18+0.j
  2.97631495e-19+0.j -2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j -2.97631495e-19+0.j  2.97631495e-19+0.j
 -3.76

In [12]:
# Measure both cases
shots = 10000
n = 7

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j  2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j -1.94518072e-18+0.j
  1.94518072e-18+0.j  2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -5.41462768e-18+0.j  5.41462768e-18+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j  2.10457248e-19+0.j
 -2.10457248e-19+0.j -2.10457248e-19+0.j  2.10457248e-19+0.j
 -1.52426623e-18+0.j  1.52426623e-18+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j  2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j -5.41462768e-18+0.j
  5.41462768e-18+0.j  2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j -1.52426623e-18+0.j  1.52426623e-18+0.j
 -2.10457248e-19+0.j  2.10457248e-19+0.j -2.10457248e-19+0.j
  2.10457248e-19+0.j  2.10457248e-19+0.j -2.10457248e-19+0.j
 -1.52

In [13]:
# Measure both cases
shots = 10000
n = 6

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j -2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j -3.17181546e-18+0.j
  3.17181546e-18+0.j -2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  3.76707845e-18+0.j -3.76707845e-18+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j -2.97631495e-19+0.j
  2.97631495e-19+0.j  2.97631495e-19+0.j -2.97631495e-19+0.j
 -3.76707845e-18+0.j  3.76707845e-18+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j -2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j  1.76448663e-17+0.j
 -1.76448663e-17+0.j -2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j  2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j -3.76707845e-18+0.j  3.76707845e-18+0.j
  2.97631495e-19+0.j -2.97631495e-19+0.j  2.97631495e-19+0.j
 -2.97631495e-19+0.j -2.97631495e-19+0.j  2.97631495e-19+0.j
 -3.76

In [14]:
# Measure both cases
shots = 20000
n = 2

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j -1.14967359e-17+0.j
  1.14967359e-17+0.j -1.14967359e-17+0.j  1.14967359e-17+0.j
 -1.62588398e-17+0.j  1.62588398e-17+0.j]

 state balanced:
 [ 1.14967359e-17+0.j -1.14967359e-17+0.j  7.07106781e-01+0.j
 -7.07106781e-01+0.j  1.62588398e-17+0.j -1.62588398e-17+0.j
  1.14967359e-17+0.j -1.14967359e-17+0.j]

Measurement samples (constant):
 Counter({np.int64(0): 20000})

Measurement samples (balanced):
 Counter({np.int64(1): 20000})


In [16]:
# Measure both cases
shots = 20000
n = 2

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j -1.14967359e-17+0.j
  1.14967359e-17+0.j -1.14967359e-17+0.j  1.14967359e-17+0.j
 -1.62588398e-17+0.j  1.62588398e-17+0.j]

 state balanced:
 [ 1.14967359e-17+0.j -1.14967359e-17+0.j  7.07106781e-01+0.j
 -7.07106781e-01+0.j  1.62588398e-17+0.j -1.62588398e-17+0.j
  1.14967359e-17+0.j -1.14967359e-17+0.j]

Measurement samples (constant):
 Counter({np.int64(0): 20000})

Measurement samples (balanced):
 Counter({np.int64(1): 20000})


In [17]:
shots = 20000
n = 3

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j -1.68365798e-18+0.j
  1.68365798e-18+0.j -1.68365798e-18+0.j  1.68365798e-18+0.j
  1.68365798e-18+0.j -1.68365798e-18+0.j -2.94392336e-17+0.j
  2.94392336e-17+0.j  1.68365798e-18+0.j -1.68365798e-18+0.j
  1.68365798e-18+0.j -1.68365798e-18+0.j -1.68365798e-18+0.j
  1.68365798e-18+0.j]

 state balanced:
 [ 1.68365798e-18+0.j -1.68365798e-18+0.j  7.07106781e-01+0.j
 -7.07106781e-01+0.j -1.68365798e-18+0.j  1.68365798e-18+0.j
  1.68365798e-18+0.j -1.68365798e-18+0.j -1.68365798e-18+0.j
  1.68365798e-18+0.j  2.94392336e-17+0.j -2.94392336e-17+0.j
  1.68365798e-18+0.j -1.68365798e-18+0.j -1.68365798e-18+0.j
  1.68365798e-18+0.j]

Measurement samples (constant):
 Counter({np.int64(0): 20000})

Measurement samples (balanced):
 Counter({np.int64(1): 20000})


In [18]:
shots = 20000
n = 4

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j -8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j  8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j -8.41828992e-19+0.j
  8.41828992e-19+0.j  8.41828992e-19+0.j -8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j -8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j  8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j  8.41828992e-19+0.j
 -8.41828992e-19+0.j -8.41828992e-19+0.j  8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j -8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j  8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j]

 state balanced:
 [ 8.41828992e-19+0.j -8.41828992e-19+0.j  7.07106781e-01+0.j
 -7.07106781e-01+0.j -8.41828992e-19+0.j  8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j -8.41828992e-19+0.j
  8.41828992e-19+0.j  8.41828992e-19+0.j -8.41828992e-19+0.j
  8.41828992e-19+0.j -8.41828992e-19+0.j -8.41828992e-19+0.j
  8.41

In [19]:
shots = 20000
n = 5

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j  5.95262989e-19+0.j
 -5.95262989e-19+0.j  5.95262989e-19+0.j -5.95262989e-19+0.j
 -5.95262989e-19+0.j  5.95262989e-19+0.j  7.53415689e-18+0.j
 -7.53415689e-18+0.j -5.95262989e-19+0.j  5.95262989e-19+0.j
 -5.95262989e-19+0.j  5.95262989e-19+0.j  5.95262989e-19+0.j
 -5.95262989e-19+0.j  2.14119447e-17+0.j -2.14119447e-17+0.j
 -5.95262989e-19+0.j  5.95262989e-19+0.j -5.95262989e-19+0.j
  5.95262989e-19+0.j  5.95262989e-19+0.j -5.95262989e-19+0.j
  6.34363091e-18+0.j -6.34363091e-18+0.j  5.95262989e-19+0.j
 -5.95262989e-19+0.j  5.95262989e-19+0.j -5.95262989e-19+0.j
 -5.95262989e-19+0.j  5.95262989e-19+0.j  4.91675203e-17+0.j
 -4.91675203e-17+0.j -5.95262989e-19+0.j  5.95262989e-19+0.j
 -5.95262989e-19+0.j  5.95262989e-19+0.j  5.95262989e-19+0.j
 -5.95262989e-19+0.j  6.34363091e-18+0.j -6.34363091e-18+0.j
  5.95262989e-19+0.j -5.95262989e-19+0.j  5.95262989e-19+0.j
 -5.95262989e-19+0.j -5.95262989e-19+0.j  5.95262989e-19+0.j
  6.34

In [20]:
shots = 20000
n = 10

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

 state constant:
 [-7.07106781e-01+0.j  7.07106781e-01+0.j  1.08967808e-20+0.j ...
  0.00000000e+00+0.j  0.00000000e+00+0.j  0.00000000e+00+0.j]

 state balanced:
 [-1.08967808e-20+0.j  1.08967808e-20+0.j  7.07106781e-01+0.j ...
  0.00000000e+00+0.j  0.00000000e+00+0.j  0.00000000e+00+0.j]

Measurement samples (constant):
 Counter({np.int64(0): 20000})

Measurement samples (balanced):
 Counter({np.int64(1): 20000})


In [1]:
shots = 20000
n = 14

state_c = deutsch_jozsa(n, f_constant_1)
state_b  = deutsch_jozsa(n, f_balanced_parity)

samples_c = sample_measurements_input(state_c, n, shots)
samples_b  = sample_measurements_input(state_b, n, shots)

print(" state constant:\n", state_c)
print()
print(" state balanced:\n", state_b)
print()
print("Measurement samples (constant):\n", samples_c)
print()
print("Measurement samples (balanced):\n", samples_b)

NameError: name 'deutsch_jozsa' is not defined